name: Meta Code-Change Hypofuzz
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install -r deps/test.txt
        python -m pip install .

    - name: Download example database
      uses: dawidd6/action-download-artifact@v2.24.3
      with:
        name: hypofuzz-example-db
        path: .hypothesis/examples


    - name: Run hypofuzz session
      continue-on-error: true
      run: |
        timeout --preserve-status 20 hypothesis fuzz --no-dashboard

    - name: Upload example database as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: hypofuzz-example-db
        path: .hypothesis/examples
